---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - sudo apt-get install ansible -y
  - sudo sed -i -e's@#roles_path.*@roles_path=../@' /etc/ansible/ansible.cfg
  - mkdir -p tests/roles/ansible-role-java
  - git clone https://github.com/vrischmann/ansible-role-java tests/roles/ansible-role-java

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo -e "myid=1"
