---
- file: path=/opt/src state=directory
- file: path=/opt/build state=directory
- file: path=/etc/supervisor/conf.d state=directory
- file: path=/var/log/zookeeper state=directory

- group: name=zookeeper system=yes
- user: name=zookeeper group=zookeeper system=yes

- get_url: url=http://ftp.heanet.ie/mirrors/www.apache.org/dist/zookeeper/zookeeper-{{zookeeper.version}}/zookeeper-{{zookeeper.version}}.tar.gz 
           dest=/opt/src/zookeeper-{{zookeeper.version}}.tar.gz
           sha256sum={{zookeeper.sha256sum}}

- command: chdir=/opt tar xzf /opt/src/zookeeper-{{zookeeper.version}}.tar.gz creates=/opt/zookeeper-{{zookeeper.version}}/bin/zkCli.sh

- file: path=/opt/zookeeper-{{zookeeper.version}} state=directory owner=zookeeper group=zookeeper recurse=yes
- file: path=/var/lib/zookeeper state=directory owner=zookeeper group=zookeeper recurse=yes

- template: src=myid dest=/var/lib/zookeeper/myid owner=zookeeper group=zookeeper
  notify:
    - restart zookeeper

- template: src=zoo.cfg dest=/opt/zookeeper-{{zookeeper.version}}/conf/zoo.cfg 
  notify:
    - restart zookeeper

- apt: name=supervisor state=present
- service: name=supervisor enabled=yes state=started
- template: src=supervisor-zookeeper.conf dest=/etc/supervisor/conf.d/zookeeper.conf
  notify:
    - restart supervisor
#  ignore_errors: True
#  register: command_result
#
#- debug: msg="stdout {{ command_result }}"
#- shell: cat /var/log/zookeeper/std*.log
