---
- file: path=/opt/src state=directory
- file: path=/opt/build state=directory
- file: path=/etc/supervisor/conf.d state=directory
- file: path=/var/log/zookeeper state=directory

- apt: name=supervisor state=present
- service: name=supervisor enabled=yes state=started
- template: src=supervisor-zookeeper.conf dest=/etc/supervisor/conf.d/zookeeper.conf
  notify:
    - reread supervisor
    - update supervisor

- group: name=zookeeper system=yes
- user: name=zookeeper group=zookeeper system=yes

- get_url: url={{  zookeeper.mirror  }}/zookeeper-{{ zookeeper.version }}/zookeeper-{{ zookeeper.version }}.tar.gz
           dest=/opt/src/zookeeper-{{ zookeeper.version }}.tar.gz
           sha256sum={{ zookeeper.sha256sum }}

- command: chdir=/opt tar xzf /opt/src/zookeeper-{{ zookeeper.version }}.tar.gz creates=/opt/zookeeper-{{ zookeeper.version }}/bin/zkCli.sh

- file: path=/opt/zookeeper-{{ zookeeper.version }} state=directory owner=zookeeper group=zookeeper recurse=yes
- file: path=/var/lib/zookeeper state=directory owner=zookeeper group=zookeeper recurse=yes

# force these to happen immediately
- name: reread supervisor
  command: supervisorctl reread

- name: update supervisor
  command: supervisorctl update

- template: src=myid dest=/var/lib/zookeeper/myid owner=zookeeper group=zookeeper
  notify:
    - restart zookeeper

- template: src=zoo.cfg dest=/opt/zookeeper-{{ zookeeper.version }}/conf/zoo.cfg
  notify:
    - restart zookeeper
